export default {
    page1() {
        let page = [
            {
              login: 'freeCodeCamp',
              id: 9892522,
              node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/9892522?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/freeCodeCamp',
              html_url: 'https://github.com/freeCodeCamp',
              followers_url: 'https://api.github.com/users/freeCodeCamp/followers',
              following_url: 'https://api.github.com/users/freeCodeCamp/following{/other_user}',
              gists_url: 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/freeCodeCamp/subscriptions',
              organizations_url: 'https://api.github.com/users/freeCodeCamp/orgs',
              repos_url: 'https://api.github.com/users/freeCodeCamp/repos',
              events_url: 'https://api.github.com/users/freeCodeCamp/events{/privacy}',
              received_events_url: 'https://api.github.com/users/freeCodeCamp/received_events',
              type: 'Organization',
              site_admin: false
            },
            {
              login: 'BerkeleyTrue',
              id: 6775919,
              node_id: 'MDQ6VXNlcjY3NzU5MTk=',
              avatar_url: 'https://avatars3.githubusercontent.com/u/6775919?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/BerkeleyTrue',
              html_url: 'https://github.com/BerkeleyTrue',
              followers_url: 'https://api.github.com/users/BerkeleyTrue/followers',
              following_url: 'https://api.github.com/users/BerkeleyTrue/following{/other_user}',
              gists_url: 'https://api.github.com/users/BerkeleyTrue/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/BerkeleyTrue/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/BerkeleyTrue/subscriptions',
              organizations_url: 'https://api.github.com/users/BerkeleyTrue/orgs',
              repos_url: 'https://api.github.com/users/BerkeleyTrue/repos',
              events_url: 'https://api.github.com/users/BerkeleyTrue/events{/privacy}',
              received_events_url: 'https://api.github.com/users/BerkeleyTrue/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'jasonmendes',
              id: 9041312,
              node_id: 'MDQ6VXNlcjkwNDEzMTI=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/9041312?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/jasonmendes',
              html_url: 'https://github.com/jasonmendes',
              followers_url: 'https://api.github.com/users/jasonmendes/followers',
              following_url: 'https://api.github.com/users/jasonmendes/following{/other_user}',
              gists_url: 'https://api.github.com/users/jasonmendes/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/jasonmendes/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/jasonmendes/subscriptions',
              organizations_url: 'https://api.github.com/users/jasonmendes/orgs',
              repos_url: 'https://api.github.com/users/jasonmendes/repos',
              events_url: 'https://api.github.com/users/jasonmendes/events{/privacy}',
              received_events_url: 'https://api.github.com/users/jasonmendes/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'bubencode',
              id: 7376026,
              node_id: 'MDQ6VXNlcjczNzYwMjY=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/7376026?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/bubencode',
              html_url: 'https://github.com/bubencode',
              followers_url: 'https://api.github.com/users/bubencode/followers',
              following_url: 'https://api.github.com/users/bubencode/following{/other_user}',
              gists_url: 'https://api.github.com/users/bubencode/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/bubencode/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/bubencode/subscriptions',
              organizations_url: 'https://api.github.com/users/bubencode/orgs',
              repos_url: 'https://api.github.com/users/bubencode/repos',
              events_url: 'https://api.github.com/users/bubencode/events{/privacy}',
              received_events_url: 'https://api.github.com/users/bubencode/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'serkanh',
              id: 947426,
              node_id: 'MDQ6VXNlcjk0NzQyNg==',
              avatar_url: 'https://avatars0.githubusercontent.com/u/947426?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/serkanh',
              html_url: 'https://github.com/serkanh',
              followers_url: 'https://api.github.com/users/serkanh/followers',
              following_url: 'https://api.github.com/users/serkanh/following{/other_user}',
              gists_url: 'https://api.github.com/users/serkanh/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/serkanh/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/serkanh/subscriptions',
              organizations_url: 'https://api.github.com/users/serkanh/orgs',
              repos_url: 'https://api.github.com/users/serkanh/repos',
              events_url: 'https://api.github.com/users/serkanh/events{/privacy}',
              received_events_url: 'https://api.github.com/users/serkanh/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'ksharifbd',
              id: 7776002,
              node_id: 'MDQ6VXNlcjc3NzYwMDI=',
              avatar_url: 'https://avatars3.githubusercontent.com/u/7776002?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/ksharifbd',
              html_url: 'https://github.com/ksharifbd',
              followers_url: 'https://api.github.com/users/ksharifbd/followers',
              following_url: 'https://api.github.com/users/ksharifbd/following{/other_user}',
              gists_url: 'https://api.github.com/users/ksharifbd/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/ksharifbd/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/ksharifbd/subscriptions',
              organizations_url: 'https://api.github.com/users/ksharifbd/orgs',
              repos_url: 'https://api.github.com/users/ksharifbd/repos',
              events_url: 'https://api.github.com/users/ksharifbd/events{/privacy}',
              received_events_url: 'https://api.github.com/users/ksharifbd/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'artificemm',
              id: 18200,
              node_id: 'MDQ6VXNlcjE4MjAw',
              avatar_url: 'https://avatars1.githubusercontent.com/u/18200?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/artificemm',
              html_url: 'https://github.com/artificemm',
              followers_url: 'https://api.github.com/users/artificemm/followers',
              following_url: 'https://api.github.com/users/artificemm/following{/other_user}',
              gists_url: 'https://api.github.com/users/artificemm/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/artificemm/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/artificemm/subscriptions',
              organizations_url: 'https://api.github.com/users/artificemm/orgs',
              repos_url: 'https://api.github.com/users/artificemm/repos',
              events_url: 'https://api.github.com/users/artificemm/events{/privacy}',
              received_events_url: 'https://api.github.com/users/artificemm/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'ertuncefeoglu',
              id: 2078621,
              node_id: 'MDQ6VXNlcjIwNzg2MjE=',
              avatar_url: 'https://avatars3.githubusercontent.com/u/2078621?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/ertuncefeoglu',
              html_url: 'https://github.com/ertuncefeoglu',
              followers_url: 'https://api.github.com/users/ertuncefeoglu/followers',
              following_url: 'https://api.github.com/users/ertuncefeoglu/following{/other_user}',
              gists_url: 'https://api.github.com/users/ertuncefeoglu/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/ertuncefeoglu/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/ertuncefeoglu/subscriptions',
              organizations_url: 'https://api.github.com/users/ertuncefeoglu/orgs',
              repos_url: 'https://api.github.com/users/ertuncefeoglu/repos',
              events_url: 'https://api.github.com/users/ertuncefeoglu/events{/privacy}',
              received_events_url: 'https://api.github.com/users/ertuncefeoglu/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'iancmason',
              id: 1485780,
              node_id: 'MDQ6VXNlcjE0ODU3ODA=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/1485780?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/iancmason',
              html_url: 'https://github.com/iancmason',
              followers_url: 'https://api.github.com/users/iancmason/followers',
              following_url: 'https://api.github.com/users/iancmason/following{/other_user}',
              gists_url: 'https://api.github.com/users/iancmason/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/iancmason/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/iancmason/subscriptions',
              organizations_url: 'https://api.github.com/users/iancmason/orgs',
              repos_url: 'https://api.github.com/users/iancmason/repos',
              events_url: 'https://api.github.com/users/iancmason/events{/privacy}',
              received_events_url: 'https://api.github.com/users/iancmason/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'adamnemecek',
              id: 182415,
              node_id: 'MDQ6VXNlcjE4MjQxNQ==',
              avatar_url: 'https://avatars2.githubusercontent.com/u/182415?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/adamnemecek',
              html_url: 'https://github.com/adamnemecek',
              followers_url: 'https://api.github.com/users/adamnemecek/followers',
              following_url: 'https://api.github.com/users/adamnemecek/following{/other_user}',
              gists_url: 'https://api.github.com/users/adamnemecek/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/adamnemecek/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/adamnemecek/subscriptions',
              organizations_url: 'https://api.github.com/users/adamnemecek/orgs',
              repos_url: 'https://api.github.com/users/adamnemecek/repos',
              events_url: 'https://api.github.com/users/adamnemecek/events{/privacy}',
              received_events_url: 'https://api.github.com/users/adamnemecek/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'sleepy-cat',
              id: 1391125,
              node_id: 'MDQ6VXNlcjEzOTExMjU=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/1391125?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/sleepy-cat',
              html_url: 'https://github.com/sleepy-cat',
              followers_url: 'https://api.github.com/users/sleepy-cat/followers',
              following_url: 'https://api.github.com/users/sleepy-cat/following{/other_user}',
              gists_url: 'https://api.github.com/users/sleepy-cat/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/sleepy-cat/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/sleepy-cat/subscriptions',
              organizations_url: 'https://api.github.com/users/sleepy-cat/orgs',
              repos_url: 'https://api.github.com/users/sleepy-cat/repos',
              events_url: 'https://api.github.com/users/sleepy-cat/events{/privacy}',
              received_events_url: 'https://api.github.com/users/sleepy-cat/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'tooqinc',
              id: 5984407,
              node_id: 'MDQ6VXNlcjU5ODQ0MDc=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/5984407?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/tooqinc',
              html_url: 'https://github.com/tooqinc',
              followers_url: 'https://api.github.com/users/tooqinc/followers',
              following_url: 'https://api.github.com/users/tooqinc/following{/other_user}',
              gists_url: 'https://api.github.com/users/tooqinc/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/tooqinc/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/tooqinc/subscriptions',
              organizations_url: 'https://api.github.com/users/tooqinc/orgs',
              repos_url: 'https://api.github.com/users/tooqinc/repos',
              events_url: 'https://api.github.com/users/tooqinc/events{/privacy}',
              received_events_url: 'https://api.github.com/users/tooqinc/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'levonk',
              id: 277861,
              node_id: 'MDQ6VXNlcjI3Nzg2MQ==',
              avatar_url: 'https://avatars0.githubusercontent.com/u/277861?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/levonk',
              html_url: 'https://github.com/levonk',
              followers_url: 'https://api.github.com/users/levonk/followers',
              following_url: 'https://api.github.com/users/levonk/following{/other_user}',
              gists_url: 'https://api.github.com/users/levonk/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/levonk/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/levonk/subscriptions',
              organizations_url: 'https://api.github.com/users/levonk/orgs',
              repos_url: 'https://api.github.com/users/levonk/repos',
              events_url: 'https://api.github.com/users/levonk/events{/privacy}',
              received_events_url: 'https://api.github.com/users/levonk/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'kaplejon',
              id: 5133819,
              node_id: 'MDQ6VXNlcjUxMzM4MTk=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/5133819?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/kaplejon',
              html_url: 'https://github.com/kaplejon',
              followers_url: 'https://api.github.com/users/kaplejon/followers',
              following_url: 'https://api.github.com/users/kaplejon/following{/other_user}',
              gists_url: 'https://api.github.com/users/kaplejon/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/kaplejon/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/kaplejon/subscriptions',
              organizations_url: 'https://api.github.com/users/kaplejon/orgs',
              repos_url: 'https://api.github.com/users/kaplejon/repos',
              events_url: 'https://api.github.com/users/kaplejon/events{/privacy}',
              received_events_url: 'https://api.github.com/users/kaplejon/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'zachshallbetter',
              id: 949434,
              node_id: 'MDQ6VXNlcjk0OTQzNA==',
              avatar_url: 'https://avatars3.githubusercontent.com/u/949434?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/zachshallbetter',
              html_url: 'https://github.com/zachshallbetter',
              followers_url: 'https://api.github.com/users/zachshallbetter/followers',
              following_url: 'https://api.github.com/users/zachshallbetter/following{/other_user}',
              gists_url: 'https://api.github.com/users/zachshallbetter/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/zachshallbetter/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/zachshallbetter/subscriptions',
              organizations_url: 'https://api.github.com/users/zachshallbetter/orgs',
              repos_url: 'https://api.github.com/users/zachshallbetter/repos',
              events_url: 'https://api.github.com/users/zachshallbetter/events{/privacy}',
              received_events_url: 'https://api.github.com/users/zachshallbetter/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'notnorth',
              id: 10211436,
              node_id: 'MDQ6VXNlcjEwMjExNDM2',
              avatar_url: 'https://avatars2.githubusercontent.com/u/10211436?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/notnorth',
              html_url: 'https://github.com/notnorth',
              followers_url: 'https://api.github.com/users/notnorth/followers',
              following_url: 'https://api.github.com/users/notnorth/following{/other_user}',
              gists_url: 'https://api.github.com/users/notnorth/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/notnorth/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/notnorth/subscriptions',
              organizations_url: 'https://api.github.com/users/notnorth/orgs',
              repos_url: 'https://api.github.com/users/notnorth/repos',
              events_url: 'https://api.github.com/users/notnorth/events{/privacy}',
              received_events_url: 'https://api.github.com/users/notnorth/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'robertboloc',
              id: 507871,
              node_id: 'MDQ6VXNlcjUwNzg3MQ==',
              avatar_url: 'https://avatars1.githubusercontent.com/u/507871?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/robertboloc',
              html_url: 'https://github.com/robertboloc',
              followers_url: 'https://api.github.com/users/robertboloc/followers',
              following_url: 'https://api.github.com/users/robertboloc/following{/other_user}',
              gists_url: 'https://api.github.com/users/robertboloc/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/robertboloc/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/robertboloc/subscriptions',
              organizations_url: 'https://api.github.com/users/robertboloc/orgs',
              repos_url: 'https://api.github.com/users/robertboloc/repos',
              events_url: 'https://api.github.com/users/robertboloc/events{/privacy}',
              received_events_url: 'https://api.github.com/users/robertboloc/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'lvnilesh',
              id: 93558,
              node_id: 'MDQ6VXNlcjkzNTU4',
              avatar_url: 'https://avatars3.githubusercontent.com/u/93558?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/lvnilesh',
              html_url: 'https://github.com/lvnilesh',
              followers_url: 'https://api.github.com/users/lvnilesh/followers',
              following_url: 'https://api.github.com/users/lvnilesh/following{/other_user}',
              gists_url: 'https://api.github.com/users/lvnilesh/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/lvnilesh/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/lvnilesh/subscriptions',
              organizations_url: 'https://api.github.com/users/lvnilesh/orgs',
              repos_url: 'https://api.github.com/users/lvnilesh/repos',
              events_url: 'https://api.github.com/users/lvnilesh/events{/privacy}',
              received_events_url: 'https://api.github.com/users/lvnilesh/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'jakblak',
              id: 5496929,
              node_id: 'MDQ6VXNlcjU0OTY5Mjk=',
              avatar_url: 'https://avatars2.githubusercontent.com/u/5496929?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/jakblak',
              html_url: 'https://github.com/jakblak',
              followers_url: 'https://api.github.com/users/jakblak/followers',
              following_url: 'https://api.github.com/users/jakblak/following{/other_user}',
              gists_url: 'https://api.github.com/users/jakblak/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/jakblak/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/jakblak/subscriptions',
              organizations_url: 'https://api.github.com/users/jakblak/orgs',
              repos_url: 'https://api.github.com/users/jakblak/repos',
              events_url: 'https://api.github.com/users/jakblak/events{/privacy}',
              received_events_url: 'https://api.github.com/users/jakblak/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'holyxiaoxin',
              id: 5796213,
              node_id: 'MDQ6VXNlcjU3OTYyMTM=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/5796213?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/holyxiaoxin',
              html_url: 'https://github.com/holyxiaoxin',
              followers_url: 'https://api.github.com/users/holyxiaoxin/followers',
              following_url: 'https://api.github.com/users/holyxiaoxin/following{/other_user}',
              gists_url: 'https://api.github.com/users/holyxiaoxin/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/holyxiaoxin/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/holyxiaoxin/subscriptions',
              organizations_url: 'https://api.github.com/users/holyxiaoxin/orgs',
              repos_url: 'https://api.github.com/users/holyxiaoxin/repos',
              events_url: 'https://api.github.com/users/holyxiaoxin/events{/privacy}',
              received_events_url: 'https://api.github.com/users/holyxiaoxin/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'sibbl',
              id: 866535,
              node_id: 'MDQ6VXNlcjg2NjUzNQ==',
              avatar_url: 'https://avatars3.githubusercontent.com/u/866535?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/sibbl',
              html_url: 'https://github.com/sibbl',
              followers_url: 'https://api.github.com/users/sibbl/followers',
              following_url: 'https://api.github.com/users/sibbl/following{/other_user}',
              gists_url: 'https://api.github.com/users/sibbl/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/sibbl/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/sibbl/subscriptions',
              organizations_url: 'https://api.github.com/users/sibbl/orgs',
              repos_url: 'https://api.github.com/users/sibbl/repos',
              events_url: 'https://api.github.com/users/sibbl/events{/privacy}',
              received_events_url: 'https://api.github.com/users/sibbl/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'afaqurk',
              id: 751323,
              node_id: 'MDQ6VXNlcjc1MTMyMw==',
              avatar_url: 'https://avatars1.githubusercontent.com/u/751323?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/afaqurk',
              html_url: 'https://github.com/afaqurk',
              followers_url: 'https://api.github.com/users/afaqurk/followers',
              following_url: 'https://api.github.com/users/afaqurk/following{/other_user}',
              gists_url: 'https://api.github.com/users/afaqurk/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/afaqurk/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/afaqurk/subscriptions',
              organizations_url: 'https://api.github.com/users/afaqurk/orgs',
              repos_url: 'https://api.github.com/users/afaqurk/repos',
              events_url: 'https://api.github.com/users/afaqurk/events{/privacy}',
              received_events_url: 'https://api.github.com/users/afaqurk/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'N0FJ',
              id: 4180569,
              node_id: 'MDQ6VXNlcjQxODA1Njk=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/4180569?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/N0FJ',
              html_url: 'https://github.com/N0FJ',
              followers_url: 'https://api.github.com/users/N0FJ/followers',
              following_url: 'https://api.github.com/users/N0FJ/following{/other_user}',
              gists_url: 'https://api.github.com/users/N0FJ/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/N0FJ/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/N0FJ/subscriptions',
              organizations_url: 'https://api.github.com/users/N0FJ/orgs',
              repos_url: 'https://api.github.com/users/N0FJ/repos',
              events_url: 'https://api.github.com/users/N0FJ/events{/privacy}',
              received_events_url: 'https://api.github.com/users/N0FJ/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'tioteath',
              id: 7210800,
              node_id: 'MDQ6VXNlcjcyMTA4MDA=',
              avatar_url: 'https://avatars1.githubusercontent.com/u/7210800?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/tioteath',
              html_url: 'https://github.com/tioteath',
              followers_url: 'https://api.github.com/users/tioteath/followers',
              following_url: 'https://api.github.com/users/tioteath/following{/other_user}',
              gists_url: 'https://api.github.com/users/tioteath/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/tioteath/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/tioteath/subscriptions',
              organizations_url: 'https://api.github.com/users/tioteath/orgs',
              repos_url: 'https://api.github.com/users/tioteath/repos',
              events_url: 'https://api.github.com/users/tioteath/events{/privacy}',
              received_events_url: 'https://api.github.com/users/tioteath/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'mrsmartpants',
              id: 5080834,
              node_id: 'MDQ6VXNlcjUwODA4MzQ=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/5080834?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/mrsmartpants',
              html_url: 'https://github.com/mrsmartpants',
              followers_url: 'https://api.github.com/users/mrsmartpants/followers',
              following_url: 'https://api.github.com/users/mrsmartpants/following{/other_user}',
              gists_url: 'https://api.github.com/users/mrsmartpants/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/mrsmartpants/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/mrsmartpants/subscriptions',
              organizations_url: 'https://api.github.com/users/mrsmartpants/orgs',
              repos_url: 'https://api.github.com/users/mrsmartpants/repos',
              events_url: 'https://api.github.com/users/mrsmartpants/events{/privacy}',
              received_events_url: 'https://api.github.com/users/mrsmartpants/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'pmaingi',
              id: 612859,
              node_id: 'MDQ6VXNlcjYxMjg1OQ==',
              avatar_url: 'https://avatars3.githubusercontent.com/u/612859?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/pmaingi',
              html_url: 'https://github.com/pmaingi',
              followers_url: 'https://api.github.com/users/pmaingi/followers',
              following_url: 'https://api.github.com/users/pmaingi/following{/other_user}',
              gists_url: 'https://api.github.com/users/pmaingi/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/pmaingi/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/pmaingi/subscriptions',
              organizations_url: 'https://api.github.com/users/pmaingi/orgs',
              repos_url: 'https://api.github.com/users/pmaingi/repos',
              events_url: 'https://api.github.com/users/pmaingi/events{/privacy}',
              received_events_url: 'https://api.github.com/users/pmaingi/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'johncipponeri',
              id: 5194052,
              node_id: 'MDQ6VXNlcjUxOTQwNTI=',
              avatar_url: 'https://avatars1.githubusercontent.com/u/5194052?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/johncipponeri',
              html_url: 'https://github.com/johncipponeri',
              followers_url: 'https://api.github.com/users/johncipponeri/followers',
              following_url: 'https://api.github.com/users/johncipponeri/following{/other_user}',
              gists_url: 'https://api.github.com/users/johncipponeri/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/johncipponeri/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/johncipponeri/subscriptions',
              organizations_url: 'https://api.github.com/users/johncipponeri/orgs',
              repos_url: 'https://api.github.com/users/johncipponeri/repos',
              events_url: 'https://api.github.com/users/johncipponeri/events{/privacy}',
              received_events_url: 'https://api.github.com/users/johncipponeri/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'Ting-y',
              id: 5705890,
              node_id: 'MDQ6VXNlcjU3MDU4OTA=',
              avatar_url: 'https://avatars3.githubusercontent.com/u/5705890?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Ting-y',
              html_url: 'https://github.com/Ting-y',
              followers_url: 'https://api.github.com/users/Ting-y/followers',
              following_url: 'https://api.github.com/users/Ting-y/following{/other_user}',
              gists_url: 'https://api.github.com/users/Ting-y/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Ting-y/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Ting-y/subscriptions',
              organizations_url: 'https://api.github.com/users/Ting-y/orgs',
              repos_url: 'https://api.github.com/users/Ting-y/repos',
              events_url: 'https://api.github.com/users/Ting-y/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Ting-y/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'twoflowers',
              id: 515426,
              node_id: 'MDQ6VXNlcjUxNTQyNg==',
              avatar_url: 'https://avatars0.githubusercontent.com/u/515426?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/twoflowers',
              html_url: 'https://github.com/twoflowers',
              followers_url: 'https://api.github.com/users/twoflowers/followers',
              following_url: 'https://api.github.com/users/twoflowers/following{/other_user}',
              gists_url: 'https://api.github.com/users/twoflowers/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/twoflowers/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/twoflowers/subscriptions',
              organizations_url: 'https://api.github.com/users/twoflowers/orgs',
              repos_url: 'https://api.github.com/users/twoflowers/repos',
              events_url: 'https://api.github.com/users/twoflowers/events{/privacy}',
              received_events_url: 'https://api.github.com/users/twoflowers/received_events',
              type: 'User',
              site_admin: false
            },
            {
              login: 'Swelly',
              id: 3290094,
              node_id: 'MDQ6VXNlcjMyOTAwOTQ=',
              avatar_url: 'https://avatars0.githubusercontent.com/u/3290094?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Swelly',
              html_url: 'https://github.com/Swelly',
              followers_url: 'https://api.github.com/users/Swelly/followers',
              following_url: 'https://api.github.com/users/Swelly/following{/other_user}',
              gists_url: 'https://api.github.com/users/Swelly/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Swelly/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Swelly/subscriptions',
              organizations_url: 'https://api.github.com/users/Swelly/orgs',
              repos_url: 'https://api.github.com/users/Swelly/repos',
              events_url: 'https://api.github.com/users/Swelly/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Swelly/received_events',
              type: 'User',
              site_admin: false
            }
        ]
        return new Promise(function(resolve, reject) {
            setTimeout(function() {
                resolve(page)
             }, 100);
       })
    },
    page2() {
        let page = [
            {
            login: 'pabloangeletti',
            id: 1434676,
            node_id: 'MDQ6VXNlcjE0MzQ2NzY=',
            avatar_url: 'https://avatars0.githubusercontent.com/u/1434676?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/pabloangeletti',
            html_url: 'https://github.com/pabloangeletti',
            followers_url: 'https://api.github.com/users/pabloangeletti/followers',
            following_url: 'https://api.github.com/users/pabloangeletti/following{/other_user}',
            gists_url: 'https://api.github.com/users/pabloangeletti/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/pabloangeletti/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/pabloangeletti/subscriptions',
            organizations_url: 'https://api.github.com/users/pabloangeletti/orgs',
            repos_url: 'https://api.github.com/users/pabloangeletti/repos',
            events_url: 'https://api.github.com/users/pabloangeletti/events{/privacy}',
            received_events_url: 'https://api.github.com/users/pabloangeletti/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'binocarlos',
            id: 1676629,
            node_id: 'MDQ6VXNlcjE2NzY2Mjk=',
            avatar_url: 'https://avatars2.githubusercontent.com/u/1676629?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/binocarlos',
            html_url: 'https://github.com/binocarlos',
            followers_url: 'https://api.github.com/users/binocarlos/followers',
            following_url: 'https://api.github.com/users/binocarlos/following{/other_user}',
            gists_url: 'https://api.github.com/users/binocarlos/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/binocarlos/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/binocarlos/subscriptions',
            organizations_url: 'https://api.github.com/users/binocarlos/orgs',
            repos_url: 'https://api.github.com/users/binocarlos/repos',
            events_url: 'https://api.github.com/users/binocarlos/events{/privacy}',
            received_events_url: 'https://api.github.com/users/binocarlos/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'jinpark',
            id: 1847812,
            node_id: 'MDQ6VXNlcjE4NDc4MTI=',
            avatar_url: 'https://avatars0.githubusercontent.com/u/1847812?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/jinpark',
            html_url: 'https://github.com/jinpark',
            followers_url: 'https://api.github.com/users/jinpark/followers',
            following_url: 'https://api.github.com/users/jinpark/following{/other_user}',
            gists_url: 'https://api.github.com/users/jinpark/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/jinpark/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/jinpark/subscriptions',
            organizations_url: 'https://api.github.com/users/jinpark/orgs',
            repos_url: 'https://api.github.com/users/jinpark/repos',
            events_url: 'https://api.github.com/users/jinpark/events{/privacy}',
            received_events_url: 'https://api.github.com/users/jinpark/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'rmelfi',
            id: 1041809,
            node_id: 'MDQ6VXNlcjEwNDE4MDk=',
            avatar_url: 'https://avatars3.githubusercontent.com/u/1041809?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/rmelfi',
            html_url: 'https://github.com/rmelfi',
            followers_url: 'https://api.github.com/users/rmelfi/followers',
            following_url: 'https://api.github.com/users/rmelfi/following{/other_user}',
            gists_url: 'https://api.github.com/users/rmelfi/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/rmelfi/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/rmelfi/subscriptions',
            organizations_url: 'https://api.github.com/users/rmelfi/orgs',
            repos_url: 'https://api.github.com/users/rmelfi/repos',
            events_url: 'https://api.github.com/users/rmelfi/events{/privacy}',
            received_events_url: 'https://api.github.com/users/rmelfi/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'wonk',
            id: 923737,
            node_id: 'MDQ6VXNlcjkyMzczNw==',
            avatar_url: 'https://avatars0.githubusercontent.com/u/923737?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/wonk',
            html_url: 'https://github.com/wonk',
            followers_url: 'https://api.github.com/users/wonk/followers',
            following_url: 'https://api.github.com/users/wonk/following{/other_user}',
            gists_url: 'https://api.github.com/users/wonk/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/wonk/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/wonk/subscriptions',
            organizations_url: 'https://api.github.com/users/wonk/orgs',
            repos_url: 'https://api.github.com/users/wonk/repos',
            events_url: 'https://api.github.com/users/wonk/events{/privacy}',
            received_events_url: 'https://api.github.com/users/wonk/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'Wynda',
            id: 10391627,
            node_id: 'MDQ6VXNlcjEwMzkxNjI3',
            avatar_url: 'https://avatars0.githubusercontent.com/u/10391627?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/Wynda',
            html_url: 'https://github.com/Wynda',
            followers_url: 'https://api.github.com/users/Wynda/followers',
            following_url: 'https://api.github.com/users/Wynda/following{/other_user}',
            gists_url: 'https://api.github.com/users/Wynda/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/Wynda/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/Wynda/subscriptions',
            organizations_url: 'https://api.github.com/users/Wynda/orgs',
            repos_url: 'https://api.github.com/users/Wynda/repos',
            events_url: 'https://api.github.com/users/Wynda/events{/privacy}',
            received_events_url: 'https://api.github.com/users/Wynda/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'ciromattia',
            id: 125366,
            node_id: 'MDQ6VXNlcjEyNTM2Ng==',
            avatar_url: 'https://avatars3.githubusercontent.com/u/125366?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/ciromattia',
            html_url: 'https://github.com/ciromattia',
            followers_url: 'https://api.github.com/users/ciromattia/followers',
            following_url: 'https://api.github.com/users/ciromattia/following{/other_user}',
            gists_url: 'https://api.github.com/users/ciromattia/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/ciromattia/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/ciromattia/subscriptions',
            organizations_url: 'https://api.github.com/users/ciromattia/orgs',
            repos_url: 'https://api.github.com/users/ciromattia/repos',
            events_url: 'https://api.github.com/users/ciromattia/events{/privacy}',
            received_events_url: 'https://api.github.com/users/ciromattia/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'Phonbopit',
            id: 1855019,
            node_id: 'MDQ6VXNlcjE4NTUwMTk=',
            avatar_url: 'https://avatars0.githubusercontent.com/u/1855019?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/Phonbopit',
            html_url: 'https://github.com/Phonbopit',
            followers_url: 'https://api.github.com/users/Phonbopit/followers',
            following_url: 'https://api.github.com/users/Phonbopit/following{/other_user}',
            gists_url: 'https://api.github.com/users/Phonbopit/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/Phonbopit/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/Phonbopit/subscriptions',
            organizations_url: 'https://api.github.com/users/Phonbopit/orgs',
            repos_url: 'https://api.github.com/users/Phonbopit/repos',
            events_url: 'https://api.github.com/users/Phonbopit/events{/privacy}',
            received_events_url: 'https://api.github.com/users/Phonbopit/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'courselogic',
            id: 794980,
            node_id: 'MDQ6VXNlcjc5NDk4MA==',
            avatar_url: 'https://avatars1.githubusercontent.com/u/794980?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/courselogic',
            html_url: 'https://github.com/courselogic',
            followers_url: 'https://api.github.com/users/courselogic/followers',
            following_url: 'https://api.github.com/users/courselogic/following{/other_user}',
            gists_url: 'https://api.github.com/users/courselogic/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/courselogic/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/courselogic/subscriptions',
            organizations_url: 'https://api.github.com/users/courselogic/orgs',
            repos_url: 'https://api.github.com/users/courselogic/repos',
            events_url: 'https://api.github.com/users/courselogic/events{/privacy}',
            received_events_url: 'https://api.github.com/users/courselogic/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'edsloan',
            id: 2378770,
            node_id: 'MDQ6VXNlcjIzNzg3NzA=',
            avatar_url: 'https://avatars3.githubusercontent.com/u/2378770?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/edsloan',
            html_url: 'https://github.com/edsloan',
            followers_url: 'https://api.github.com/users/edsloan/followers',
            following_url: 'https://api.github.com/users/edsloan/following{/other_user}',
            gists_url: 'https://api.github.com/users/edsloan/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/edsloan/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/edsloan/subscriptions',
            organizations_url: 'https://api.github.com/users/edsloan/orgs',
            repos_url: 'https://api.github.com/users/edsloan/repos',
            events_url: 'https://api.github.com/users/edsloan/events{/privacy}',
            received_events_url: 'https://api.github.com/users/edsloan/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'brandenbyers',
            id: 7098232,
            node_id: 'MDQ6VXNlcjcwOTgyMzI=',
            avatar_url: 'https://avatars1.githubusercontent.com/u/7098232?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/brandenbyers',
            html_url: 'https://github.com/brandenbyers',
            followers_url: 'https://api.github.com/users/brandenbyers/followers',
            following_url: 'https://api.github.com/users/brandenbyers/following{/other_user}',
            gists_url: 'https://api.github.com/users/brandenbyers/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/brandenbyers/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/brandenbyers/subscriptions',
            organizations_url: 'https://api.github.com/users/brandenbyers/orgs',
            repos_url: 'https://api.github.com/users/brandenbyers/repos',
            events_url: 'https://api.github.com/users/brandenbyers/events{/privacy}',
            received_events_url: 'https://api.github.com/users/brandenbyers/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'rosinaaa',
            id: 6076272,
            node_id: 'MDQ6VXNlcjYwNzYyNzI=',
            avatar_url: 'https://avatars3.githubusercontent.com/u/6076272?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/rosinaaa',
            html_url: 'https://github.com/rosinaaa',
            followers_url: 'https://api.github.com/users/rosinaaa/followers',
            following_url: 'https://api.github.com/users/rosinaaa/following{/other_user}',
            gists_url: 'https://api.github.com/users/rosinaaa/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/rosinaaa/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/rosinaaa/subscriptions',
            organizations_url: 'https://api.github.com/users/rosinaaa/orgs',
            repos_url: 'https://api.github.com/users/rosinaaa/repos',
            events_url: 'https://api.github.com/users/rosinaaa/events{/privacy}',
            received_events_url: 'https://api.github.com/users/rosinaaa/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'Monster52',
            id: 6055787,
            node_id: 'MDQ6VXNlcjYwNTU3ODc=',
            avatar_url: 'https://avatars0.githubusercontent.com/u/6055787?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/Monster52',
            html_url: 'https://github.com/Monster52',
            followers_url: 'https://api.github.com/users/Monster52/followers',
            following_url: 'https://api.github.com/users/Monster52/following{/other_user}',
            gists_url: 'https://api.github.com/users/Monster52/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/Monster52/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/Monster52/subscriptions',
            organizations_url: 'https://api.github.com/users/Monster52/orgs',
            repos_url: 'https://api.github.com/users/Monster52/repos',
            events_url: 'https://api.github.com/users/Monster52/events{/privacy}',
            received_events_url: 'https://api.github.com/users/Monster52/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'jasonbraun',
            id: 5950964,
            node_id: 'MDQ6VXNlcjU5NTA5NjQ=',
            avatar_url: 'https://avatars2.githubusercontent.com/u/5950964?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/jasonbraun',
            html_url: 'https://github.com/jasonbraun',
            followers_url: 'https://api.github.com/users/jasonbraun/followers',
            following_url: 'https://api.github.com/users/jasonbraun/following{/other_user}',
            gists_url: 'https://api.github.com/users/jasonbraun/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/jasonbraun/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/jasonbraun/subscriptions',
            organizations_url: 'https://api.github.com/users/jasonbraun/orgs',
            repos_url: 'https://api.github.com/users/jasonbraun/repos',
            events_url: 'https://api.github.com/users/jasonbraun/events{/privacy}',
            received_events_url: 'https://api.github.com/users/jasonbraun/received_events',
            type: 'User',
            site_admin: false
            },
            {
            login: 'jakecleary',
            id: 4572429,
            node_id: 'MDQ6VXNlcjQ1NzI0Mjk=',
            avatar_url: 'https://avatars0.githubusercontent.com/u/4572429?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/jakecleary',
            html_url: 'https://github.com/jakecleary',
            followers_url: 'https://api.github.com/users/jakecleary/followers',
            following_url: 'https://api.github.com/users/jakecleary/following{/other_user}',
            gists_url: 'https://api.github.com/users/jakecleary/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/jakecleary/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/jakecleary/subscriptions',
            organizations_url: 'https://api.github.com/users/jakecleary/orgs',
            repos_url: 'https://api.github.com/users/jakecleary/repos',
            events_url: 'https://api.github.com/users/jakecleary/events{/privacy}',
            received_events_url: 'https://api.github.com/users/jakecleary/received_events',
            type: 'User',
            site_admin: false
            }
        ]
        return new Promise(function(resolve, reject) {
            setTimeout(function() {
                resolve(page)
            }, 100);
        })
    }
}